/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GKRPC_H_RPCGEN
#define _GKRPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input_pair {
	int a;
	int b;
};
typedef struct input_pair input_pair;

typedef char *text;

#define GK_RPC 31111111
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_1(input_pair *, CLIENT *);
extern  int * add_1_svc(input_pair *, struct svc_req *);
#define sub 2
extern  int * sub_1(input_pair *, CLIENT *);
extern  int * sub_1_svc(input_pair *, struct svc_req *);
#define mult 3
extern  int * mult_1(input_pair *, CLIENT *);
extern  int * mult_1_svc(input_pair *, struct svc_req *);
#define div 4
extern  int * div_1(input_pair *, CLIENT *);
extern  int * div_1_svc(input_pair *, struct svc_req *);
#define rev_num 5
extern  int * rev_num_1(int *, CLIENT *);
extern  int * rev_num_1_svc(int *, struct svc_req *);
#define lower_to_upper 6
extern  char ** lower_to_upper_1(char **, CLIENT *);
extern  char ** lower_to_upper_1_svc(char **, struct svc_req *);
extern int gk_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_1();
extern  int * add_1_svc();
#define sub 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define mult 3
extern  int * mult_1();
extern  int * mult_1_svc();
#define div 4
extern  int * div_1();
extern  int * div_1_svc();
#define rev_num 5
extern  int * rev_num_1();
extern  int * rev_num_1_svc();
#define lower_to_upper 6
extern  char ** lower_to_upper_1();
extern  char ** lower_to_upper_1_svc();
extern int gk_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_pair (XDR *, input_pair*);
extern  bool_t xdr_text (XDR *, text*);

#else /* K&R C */
extern bool_t xdr_input_pair ();
extern bool_t xdr_text ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GKRPC_H_RPCGEN */
