/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gkrpc.h"

bool_t
xdr_input_pair (XDR *xdrs, input_pair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_text (XDR *xdrs, text *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}
