/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gkrpc.h"


int *
add_1_svc(input_pair *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->a + argp->b;
	return &result;
}

int *
sub_1_svc(input_pair *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->a - argp->b;
	return &result;
}

int *
mult_1_svc(input_pair *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->a * argp->b;
	return &result;
}

int *
div_1_svc(input_pair *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->a / argp->b;
	return &result;	
	
}

int *
rev_num_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result = 0;
	static int temp, last;
	temp = *argp;
	while(temp>0)
	{
		last = temp % 10;
		result *= 10;
		result += last;
		temp = temp / 10;
	}	
	return &result;
}

char **
lower_to_upper_1_svc(char **argp, struct svc_req *rqstp)
{
	static char temp[40];
	static char *result;
	int i = 0;
	while((*argp)[i]!='\0')
	{
		if((*argp)[i]>='a' && (*argp)[i]<='z')
			temp[i] = (*argp)[i] - ('a' - 'A');
		else
			temp[i] = (*argp)[i];
		i++;
	}
	temp[i] = '\0';
	result = temp;
	return &result;
}
